### ISSUE TITLE
Implement File api

### ISSUE THREAD

**Issue by nyxxxie** [nyxxxie/spade#26]
Because we want to add in the ability to store file history, file-specific metadata, etc, we'll need to make a custom file wrapper.  This feature is currently being worked on by @fst3a, this issue is meant as a way to formalize it and provide a forum for discussion.

Based on @fst3a and I's private conversations, I propose we implement file as follows:
`class File`  (or `SFile` or` _File`):
- `read()`, `size()`, etc (traditional file methods) implemented in a backwards compatible manner.
- `insert()`, `replace()`, and `erase()` added in addition to `write()` (`write()` will just call one of the previous 3 methods).  This will provide a better interface to an eventual change history feature.
- Handle concurrency issues with something similar to a [shared-exclusive](https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock) lock.  [This thread](http://stackoverflow.com/questions/16261902/python-any-way-to-get-one-process-to-have-a-write-lock-and-others-to-just-read) might be relevant to this feature.
- Provide ability to link with project.  This should be enforced for now (file must specify project in initializer), but it would be neat if this was optional in the future.

This will serve as a base implementation of file, with other features (change history, FileView, caching, mmaping) being implemented in other features.

**Comment by nanokatze** [comment]
Class will be called _File as it is not directly constructable by the user.  Instead, user should call `Project.open_file(id, mode, primary=False)` in order to get the `_File` object.  There are no concurrency issues in current model as neither `.insert()`, `.replace()` or `.replace()` write directly to the resource.  Instead, they store changes in the project database `changes` table, which can be applied later either to file itself or to its newly created copy.  `_File` will not be made directly constructable by the user and must necessarily to belong to a `Project`.  There will be no `_File.write()` method as it is redundant and might confuse the programmer (neither `.insert()` or `.replace()` behave like `io.RawIOBase.write()`).  History API is yet to be decided.  `_File.store_inplace(hash=current)` will write all changes to this file in place and update its `base` and `hash`.  Will throw an exception if `_File` was opened in readonly mode.  `_File.store_as(fd, hash=current)` will create a copy with changes applied and write it into `fd`.

**Comment by nanokatze** [comment]
In feature/impl-file branch: `seek`ing and `write_inplace` already work, though there are some problems still.  One of them includes: loading large files into memory fully and `_changes` will fail if any of the changes happen to be before `base` in time.

**Comment by nyxxxie** [comment]
During private conversation we agreed that I would take on development of this feature moving forward.

**Comment by nyxxxie** [comment]
Base implementation of file complete as specified in OP.
